WeatherExplorer/WeatherExplorer/Models/ErrorViewModel.cs
namespace WeatherExplorer.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WeatherExplorer/WeatherExplorer/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using WeatherExplorer.BL.Models;
using WeatherExplorer.BL.Services.Interfaces;

namespace WeatherExplorer.Controllers
{
    public class WeatherController : Controller
    {
        private readonly IFileReader _fileReader;
        private readonly IViewer _viewer;
        private readonly ILogger _logger;

        public WeatherController(IFileReader fileReader, IViewer viewer, ILogger logger)
        {
            _fileReader = fileReader;
            _viewer = viewer;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> LoaderView()
        {
            var cities = await _viewer.GetCities();
            return View("LoaderView", cities.ToList());
        }

        [HttpGet]
        public async Task<IActionResult> GetWeather(int pageNumber = 30, int? year = null, int? month = null)
        {
            var weatherData = new List<ViewWeather>();
            try
            {
                if (year > 9999 || year < 1)
                    return BadRequest("Incorrect year");

                if (month > 12 || month < 1)
                    return BadRequest("Incorrect month");

                if (pageNumber < 1)
                    return BadRequest("Count entities less then 1");

                weatherData = _viewer.GetWeather(year, month).Result.ToList();

                if (weatherData != null && pageNumber != 0)
                      weatherData.Take(pageNumber);

            }
            catch (Exception ex)
            {
                ViewBag.Message = "Failed load weather";
                _logger.LogError($"{ex.Message}\n{ex.StackTrace}");
            }
            return View("WeatherView", weatherData);

        }

        [HttpPost]
        public async Task<IActionResult> UploadData(IFormFileCollection files, string cityName)
        {
            try
            {
                foreach (var file in files)
                {
                    if (!file.FileName.Contains(".xls"))
                    {
                        ViewBag.Message = "File Upload Failed";
                        continue;
                    }

                    if (file.Length < 1)
                    {
                        ViewBag.Message = "File less then 1 byte";
                        continue;
                    }

                    using (var stream = new MemoryStream())
                    {
                        file.CopyTo(stream);
                        await _fileReader.ReadFileAsync(stream, cityName);
                    }
                }
                ViewBag.Message = "Files uploaded succesful";
            }
            catch
            {
                ViewBag.Message = "File Upload Failed";
            }

            return View("WeatherView");
        }

        [HttpPost]
        public async Task<IActionResult> AddCity(string cityName)
        {
            await _fileReader.AddCityAsync(cityName);
            var cities = await _viewer.GetCities();
            return View("LoaderView", cities.ToList());
        }
    }
}

WeatherExplorer/WeatherExplorer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeatherExplorer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WeatherExplorer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Reader" asp-action="View">WeatherExplorer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="LoaderView">File Loader</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="WeatherView">View</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WeatherExplorer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WeatherExplorer/WeatherExplorer/Views/Weather/LoaderView.cshtml
@model IEnumerable<string>

<h1>Buffered File Upload</h1>
<hr />

<form asp-controller="Weather" asp-action="UploadData" enctype="multipart/form-data" method="post">
    <input type="file" name="files" multiple />
    <br />
    <input type="text" name="cityName" />
    <br/>
    <button type="submit">Загрузить файл</button>
</form>
@if (Model == null || Model.Count() < 1)
{
    <p>Введите название города</p>
    <form asp-controller="Weather" asp-action="AddCity" method="post">
        <input type="text" name="cityName" />
        <br />
        <button type="submit">добавить город</button>
    </form>
}
else
{
    <p>Доступные города</p>
    @foreach (var city in Model)
    {
        <p>@city</p>
    }
}

@if (ViewBag.Message != null)
{
    <div class="alert" style="margin-top:20px">
        @ViewBag.Message
    </div>
}

WeatherExplorer/WeatherExplorer/Views/Weather/WeatherView.cshtml
@    using WeatherExplorer.BL;
    using WeatherExplorer.BL.Models
@model IEnumerable<ViewWeather>

@if (Model != null)
{
    <h1>Погода на @Model.FirstOrDefault()?.Date.ToString("MMMM yyyy")</h1>
    <table>
        <thead>
            <tr>
                <th>Дата</th>
                <th>Время</th>
                <th>Температура</th>
                <th>Влажность</th>
                <th>Облачно</th>
                <th>Точка росы</th>
                <th>Давление</th>
                <th>Нижние облака</th>
                <th>Горизонтальная видимость</th>
                <th>Направление ветра</th>
                <th>Скорость ветра</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var weather in Model)
            {
                <tr>
                    <td>@weather.Date.ToString("dd.MM.yyyy")</td>
                    <td>@weather.Time.ToString()</td>
                    <td>@weather.Temprature</td>
                    <td>@weather.Humidity</td>
                    <td>@weather.Cloudy</td>
                    <td>@weather.DewPoint</td>
                    <td>@weather.Pressure</td>
                    <td>@weather.LowerborderClouds</td>
                    <td>@weather.HorizontalVisibility</td>
                    <td>@weather.WindDirection</td>
                    <td>@weather.WindSpeed</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h1>No data in database</h1>
    <p>Enter data to find weather</p>
    <form asp-controller="Weather" asp-action="GetWeather" enctype="text/plain" method="get">
        <input type="text" name="pageNumber" multiple /> <p>Enter count entity for watching weather</p>
        <br />
        <input type="text" name="year" /> <p>Enter year</p>
        <br />
        <input type="text" name="month" /><p>Enter month</p>
        <br />
        <button type="submit">Find Weather by date</button>
    </form>
}